version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Costa_Rica
    open-pull-requests-limit: 3
    allow:
      - dependency-type: direct
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      npm-production-maintenance:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - "*"
        exclude-patterns:
          - "@prisma/client"
        update-types:
          - minor
          - patch
      npm-development-maintenance:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "*"
        exclude-patterns:
          - prisma
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /apps/server
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
      - dependency-name: nginx
        update-types:
          - version-update:semver-minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
